version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Lints
          command: ./gradlew --continue ktlintCheck